More answers and questions to be added here

Problems with FTP
================
Problem:
Error in logging in ftp, log shows
Error authenticating to Zope FTP server 127.0.0.1:8021                               with username manager : [Errno 111] Connection refused

Solution:
Checkout that ZServer FTP has started, on port specified on site.cfg (default is 8021)
Worker's log (worker.log) should show that it has started

 2013-05-21 16:36:43 INFO ZServer FTP server started at Tue May 21 16:36:43 2013
        Hostname: 0.0.0.0
        Port: 8021

try to telnet to that port and make sure it listens

$telnet localhost 8021
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 localhost FTP server (Medusa Async V96471 [experimental]) ready.

check that file parts/ploneftp/config.py has that address for zope_ftp_address

connection timed out during buildout
================================

If you get errors like this one

Error: Error downloading extends for URL  http://download.zope.org/zopetoolkit/index/1.0.7/zopeapp-versions.cfg: 
[Errno socket error] [Errno 110] connection timed out 

don't worry so much, some packages could not be fetched due to network issues or high load on the server they are located. 
Pypi and zope.org very often have timeout errors. Just rerun the buildout (./bin/buildout -vN) as soon as it fails with similar
errors!
